services:
  postgres:
    image: postgres:15
    container_name: world_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - world-local
networks:
  world-local:
    driver: bridge
    name: world-local