spring:
  application:
    name: backend
  profiles:
    active: local
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:file:.env[.properties]
# custom properties for world app
custom:
  mail:
    forward: ${MAIL_FORWARD}
  jwt:
    token:
      expiration: ${JWT_EXPIRATION:300000}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
custom:
  base-url: http://localhost:3000
  jwt:
    token:
      secret: ${JWT_SECRET:thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd}
  cookie:
    secure: false
springdoc:
  swagger-ui:
    # swagger-ui attach XSRF(CSRF) token in request cookie
    csrf:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # When database locates in another instance, this url must be changed
    url: jdbc:postgresql://${DATABASE_HOST}:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
custom:
  base-url: https://world.sotaro.dev
  jwt:
    token:
      secret: ${JWT_SECRET}
  cookie:
    secure: true
